name       : libayatana-indicator
version    : 0.9.3
release    : 3
source     :
    - https://github.com/AyatanaIndicators/libayatana-indicator/archive/refs/tags/0.9.3.tar.gz : 09c5456fcb430b6ee0626fafdf99a32eb8746b267d56ab2bd4c8a8dd6ca731da
license    : GPL-3.0-or-later
component  : programming.library
summary    : Common components of the libayatana project
description: |
    The Ayatana Indicators project is the continuation of Application Indicators and System Indicators, two technologies developed by Canonical Ltd. for the Unity7 desktop.
    Application Indicators are a GTK implementation of the StatusNotifierItem Specification (SNI) that was originally submitted to freedesktop.org by KDE.
replaces   :
    - libindicator
    - devel : libindicator-devel
    - 32bit : libindicator-32bit
    - 32bit-devel : libindicator-32bit-devel
emul32     : yes
builddeps  :
    - pkgconfig32(gtk+-2.0)
    - pkgconfig32(libayatana-ido3-0.4)
    - mate-common
    - vala
setup      : |
    mkdir gtk2
    pushd gtk2
        %cmake_ninja ../ -DCMAKE_INSTALL_LIBDIR=%libdir% -DFLAVOUR_GTK2=ON
    popd
    mkdir gtk3
    pushd gtk3
        %cmake_ninja ../ -DCMAKE_INSTALL_LIBDIR=%libdir% -DFLAVOUR_GTK3=ON
    popd
build      : |
    pushd gtk2
        %ninja_build
    popd
    pushd gtk3
        %ninja_build
    popd
install    : |
    pushd gtk2
        %ninja_install
    popd
    pushd gtk3
        %ninja_install
    popd